// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/internal/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListApplicationIdentitiesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListApplicationIdentitiesRequest) Reset()         { *m = ListApplicationIdentitiesRequest{} }
func (m *ListApplicationIdentitiesRequest) String() string { return proto.CompactTextString(m) }
func (*ListApplicationIdentitiesRequest) ProtoMessage()    {}
func (*ListApplicationIdentitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf1bd0c00876e46, []int{0}
}

func (m *ListApplicationIdentitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationIdentitiesRequest.Unmarshal(m, b)
}
func (m *ListApplicationIdentitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationIdentitiesRequest.Marshal(b, m, deterministic)
}
func (m *ListApplicationIdentitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationIdentitiesRequest.Merge(m, src)
}
func (m *ListApplicationIdentitiesRequest) XXX_Size() int {
	return xxx_messageInfo_ListApplicationIdentitiesRequest.Size(m)
}
func (m *ListApplicationIdentitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationIdentitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationIdentitiesRequest proto.InternalMessageInfo

type ListApplicationIdentitiesResponse struct {
	Identities           []*Identity `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListApplicationIdentitiesResponse) Reset()         { *m = ListApplicationIdentitiesResponse{} }
func (m *ListApplicationIdentitiesResponse) String() string { return proto.CompactTextString(m) }
func (*ListApplicationIdentitiesResponse) ProtoMessage()    {}
func (*ListApplicationIdentitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf1bd0c00876e46, []int{1}
}

func (m *ListApplicationIdentitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationIdentitiesResponse.Unmarshal(m, b)
}
func (m *ListApplicationIdentitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationIdentitiesResponse.Marshal(b, m, deterministic)
}
func (m *ListApplicationIdentitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationIdentitiesResponse.Merge(m, src)
}
func (m *ListApplicationIdentitiesResponse) XXX_Size() int {
	return xxx_messageInfo_ListApplicationIdentitiesResponse.Size(m)
}
func (m *ListApplicationIdentitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationIdentitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationIdentitiesResponse proto.InternalMessageInfo

func (m *ListApplicationIdentitiesResponse) GetIdentities() []*Identity {
	if m != nil {
		return m.Identities
	}
	return nil
}

type ListApplicationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListApplicationsRequest) Reset()         { *m = ListApplicationsRequest{} }
func (m *ListApplicationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListApplicationsRequest) ProtoMessage()    {}
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf1bd0c00876e46, []int{2}
}

func (m *ListApplicationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationsRequest.Unmarshal(m, b)
}
func (m *ListApplicationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationsRequest.Marshal(b, m, deterministic)
}
func (m *ListApplicationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationsRequest.Merge(m, src)
}
func (m *ListApplicationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListApplicationsRequest.Size(m)
}
func (m *ListApplicationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationsRequest proto.InternalMessageInfo

type ListApplicationsResponse struct {
	Applications         []*Application `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListApplicationsResponse) Reset()         { *m = ListApplicationsResponse{} }
func (m *ListApplicationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListApplicationsResponse) ProtoMessage()    {}
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf1bd0c00876e46, []int{3}
}

func (m *ListApplicationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationsResponse.Unmarshal(m, b)
}
func (m *ListApplicationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationsResponse.Marshal(b, m, deterministic)
}
func (m *ListApplicationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationsResponse.Merge(m, src)
}
func (m *ListApplicationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListApplicationsResponse.Size(m)
}
func (m *ListApplicationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationsResponse proto.InternalMessageInfo

func (m *ListApplicationsResponse) GetApplications() []*Application {
	if m != nil {
		return m.Applications
	}
	return nil
}

type WatchRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchRequest) Reset()         { *m = WatchRequest{} }
func (m *WatchRequest) String() string { return proto.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()    {}
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf1bd0c00876e46, []int{4}
}

func (m *WatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchRequest.Unmarshal(m, b)
}
func (m *WatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchRequest.Marshal(b, m, deterministic)
}
func (m *WatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchRequest.Merge(m, src)
}
func (m *WatchRequest) XXX_Size() int {
	return xxx_messageInfo_WatchRequest.Size(m)
}
func (m *WatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchRequest proto.InternalMessageInfo

type WatchResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchResponse) Reset()         { *m = WatchResponse{} }
func (m *WatchResponse) String() string { return proto.CompactTextString(m) }
func (*WatchResponse) ProtoMessage()    {}
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf1bd0c00876e46, []int{5}
}

func (m *WatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchResponse.Unmarshal(m, b)
}
func (m *WatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchResponse.Marshal(b, m, deterministic)
}
func (m *WatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchResponse.Merge(m, src)
}
func (m *WatchResponse) XXX_Size() int {
	return xxx_messageInfo_WatchResponse.Size(m)
}
func (m *WatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WatchResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListApplicationIdentitiesRequest)(nil), "dogma.config.v1.ListApplicationIdentitiesRequest")
	proto.RegisterType((*ListApplicationIdentitiesResponse)(nil), "dogma.config.v1.ListApplicationIdentitiesResponse")
	proto.RegisterType((*ListApplicationsRequest)(nil), "dogma.config.v1.ListApplicationsRequest")
	proto.RegisterType((*ListApplicationsResponse)(nil), "dogma.config.v1.ListApplicationsResponse")
	proto.RegisterType((*WatchRequest)(nil), "dogma.config.v1.WatchRequest")
	proto.RegisterType((*WatchResponse)(nil), "dogma.config.v1.WatchResponse")
}

func init() {
	proto.RegisterFile("api/internal/pb/service.proto", fileDescriptor_cbf1bd0c00876e46)
}

var fileDescriptor_cbf1bd0c00876e46 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x83, 0x46, 0x0e, 0x23, 0x8a, 0xd9, 0x8b, 0x80, 0x62, 0xb0, 0x27, 0x3c, 0xb8, 0x2b,
	0x78, 0xf2, 0xe6, 0x9f, 0x8b, 0x26, 0x9e, 0xb8, 0x98, 0x18, 0x63, 0xb2, 0x2d, 0x6b, 0x99, 0x08,
	0xbb, 0x4b, 0x77, 0x20, 0xe1, 0xea, 0x27, 0xf3, 0xa3, 0x99, 0xb4, 0x6b, 0x53, 0xdb, 0x20, 0x7a,
	0xec, 0xcc, 0x7b, 0xef, 0xd7, 0x7d, 0x19, 0xe8, 0x4a, 0x8b, 0x02, 0x35, 0xa9, 0x44, 0xcb, 0xa9,
	0xb0, 0xa1, 0x70, 0x2a, 0x59, 0x62, 0xa4, 0xb8, 0x4d, 0x0c, 0x19, 0xd6, 0x1c, 0x9b, 0x78, 0x26,
	0x79, 0x64, 0xf4, 0x1b, 0xc6, 0x7c, 0x39, 0xe8, 0x1c, 0x95, 0xf5, 0xb4, 0xb2, 0xca, 0x65, 0xea,
	0x20, 0x80, 0xde, 0x23, 0x3a, 0xba, 0xb1, 0x76, 0x8a, 0x91, 0x24, 0x34, 0xfa, 0x61, 0xac, 0x34,
	0x21, 0xa1, 0x72, 0x23, 0x35, 0x5f, 0x28, 0x47, 0xc1, 0x2b, 0x9c, 0xfe, 0xa2, 0x71, 0xd6, 0x68,
	0xa7, 0xd8, 0x15, 0x00, 0xe6, 0xd3, 0x56, 0xad, 0xb7, 0xdd, 0xdf, 0x1d, 0xb6, 0x79, 0xe9, 0x5f,
	0xb8, 0x37, 0xae, 0x46, 0x05, 0x71, 0xd0, 0x86, 0xc3, 0x52, 0x7e, 0x8e, 0x7e, 0x81, 0x56, 0x75,
	0xe5, 0x89, 0xd7, 0xd0, 0x90, 0x85, 0xb9, 0x67, 0x1e, 0x57, 0x98, 0x05, 0xf3, 0xe8, 0x87, 0x23,
	0xd8, 0x87, 0xc6, 0x93, 0xa4, 0x68, 0xf2, 0x4d, 0x6b, 0xc2, 0x9e, 0xff, 0xce, 0x10, 0xc3, 0xcf,
	0x2d, 0xa8, 0xdf, 0xa5, 0x41, 0xec, 0xa3, 0x06, 0xed, 0xb5, 0x2d, 0xb0, 0x41, 0x85, 0xba, 0xa9,
	0xd5, 0xce, 0xf0, 0x3f, 0x16, 0xff, 0xe4, 0x18, 0x0e, 0xca, 0x75, 0xb0, 0xfe, 0xa6, 0x9c, 0x9c,
	0x78, 0xf6, 0x07, 0xa5, 0x07, 0xdd, 0xc3, 0x4e, 0xda, 0x04, 0xeb, 0x56, 0x3c, 0xc5, 0xc6, 0x3a,
	0x27, 0xeb, 0xd6, 0x59, 0xce, 0x45, 0xed, 0x56, 0x3c, 0x9f, 0xc7, 0x48, 0x93, 0x45, 0xc8, 0x23,
	0x33, 0x13, 0xa9, 0x9a, 0x70, 0x2e, 0x32, 0xc3, 0x3b, 0x92, 0x28, 0x5d, 0x67, 0x58, 0x4f, 0x0f,
	0xf3, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x02, 0x7d, 0xb7, 0xe7, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ConfigClient is the client API for Config service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigClient interface {
	// ListApplicationIdentities returns the identity of all applications.
	ListApplicationIdentities(ctx context.Context, in *ListApplicationIdentitiesRequest, opts ...grpc.CallOption) (*ListApplicationIdentitiesResponse, error)
	// ListApplications returns the full configuration of all applications.
	ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ListApplicationsResponse, error)
	// Watch opens a stream that sends no content, simply to detect when the
	// server goes away.
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (Config_WatchClient, error)
}

type configClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigClient(cc grpc.ClientConnInterface) ConfigClient {
	return &configClient{cc}
}

func (c *configClient) ListApplicationIdentities(ctx context.Context, in *ListApplicationIdentitiesRequest, opts ...grpc.CallOption) (*ListApplicationIdentitiesResponse, error) {
	out := new(ListApplicationIdentitiesResponse)
	err := c.cc.Invoke(ctx, "/dogma.config.v1.Config/ListApplicationIdentities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configClient) ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ListApplicationsResponse, error) {
	out := new(ListApplicationsResponse)
	err := c.cc.Invoke(ctx, "/dogma.config.v1.Config/ListApplications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (Config_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Config_serviceDesc.Streams[0], "/dogma.config.v1.Config/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &configWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Config_WatchClient interface {
	Recv() (*WatchResponse, error)
	grpc.ClientStream
}

type configWatchClient struct {
	grpc.ClientStream
}

func (x *configWatchClient) Recv() (*WatchResponse, error) {
	m := new(WatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConfigServer is the server API for Config service.
type ConfigServer interface {
	// ListApplicationIdentities returns the identity of all applications.
	ListApplicationIdentities(context.Context, *ListApplicationIdentitiesRequest) (*ListApplicationIdentitiesResponse, error)
	// ListApplications returns the full configuration of all applications.
	ListApplications(context.Context, *ListApplicationsRequest) (*ListApplicationsResponse, error)
	// Watch opens a stream that sends no content, simply to detect when the
	// server goes away.
	Watch(*WatchRequest, Config_WatchServer) error
}

// UnimplementedConfigServer can be embedded to have forward compatible implementations.
type UnimplementedConfigServer struct {
}

func (*UnimplementedConfigServer) ListApplicationIdentities(ctx context.Context, req *ListApplicationIdentitiesRequest) (*ListApplicationIdentitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApplicationIdentities not implemented")
}
func (*UnimplementedConfigServer) ListApplications(ctx context.Context, req *ListApplicationsRequest) (*ListApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApplications not implemented")
}
func (*UnimplementedConfigServer) Watch(req *WatchRequest, srv Config_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}

func RegisterConfigServer(s *grpc.Server, srv ConfigServer) {
	s.RegisterService(&_Config_serviceDesc, srv)
}

func _Config_ListApplicationIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServer).ListApplicationIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dogma.config.v1.Config/ListApplicationIdentities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServer).ListApplicationIdentities(ctx, req.(*ListApplicationIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Config_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dogma.config.v1.Config/ListApplications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServer).ListApplications(ctx, req.(*ListApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Config_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigServer).Watch(m, &configWatchServer{stream})
}

type Config_WatchServer interface {
	Send(*WatchResponse) error
	grpc.ServerStream
}

type configWatchServer struct {
	grpc.ServerStream
}

func (x *configWatchServer) Send(m *WatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Config_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dogma.config.v1.Config",
	HandlerType: (*ConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApplicationIdentities",
			Handler:    _Config_ListApplicationIdentities_Handler,
		},
		{
			MethodName: "ListApplications",
			Handler:    _Config_ListApplications_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Config_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/internal/pb/service.proto",
}
