// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/internal/pb/types.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MessageRole is a protocol buffers representation of the
// configkit/message.Role enumeration.
type MessageRole int32

const (
	MessageRole_UNKNOWN_MESSAGE_ROLE MessageRole = 0
	MessageRole_COMMAND              MessageRole = 1
	MessageRole_EVENT                MessageRole = 2
	MessageRole_TIMEOUT              MessageRole = 3
)

var MessageRole_name = map[int32]string{
	0: "UNKNOWN_MESSAGE_ROLE",
	1: "COMMAND",
	2: "EVENT",
	3: "TIMEOUT",
}

var MessageRole_value = map[string]int32{
	"UNKNOWN_MESSAGE_ROLE": 0,
	"COMMAND":              1,
	"EVENT":                2,
	"TIMEOUT":              3,
}

func (x MessageRole) String() string {
	return proto.EnumName(MessageRole_name, int32(x))
}

func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_565b712cd72dd24a, []int{0}
}

// HandlerType is a protocol buffers representation of the configkit.HandlerType
// enumeration.
type HandlerType int32

const (
	HandlerType_UNKNOWN_HANDLER_TYPE HandlerType = 0
	HandlerType_AGGREGATE            HandlerType = 1
	HandlerType_PROCESS              HandlerType = 2
	HandlerType_INTEGRATION          HandlerType = 3
	HandlerType_PROJECTION           HandlerType = 4
)

var HandlerType_name = map[int32]string{
	0: "UNKNOWN_HANDLER_TYPE",
	1: "AGGREGATE",
	2: "PROCESS",
	3: "INTEGRATION",
	4: "PROJECTION",
}

var HandlerType_value = map[string]int32{
	"UNKNOWN_HANDLER_TYPE": 0,
	"AGGREGATE":            1,
	"PROCESS":              2,
	"INTEGRATION":          3,
	"PROJECTION":           4,
}

func (x HandlerType) String() string {
	return proto.EnumName(HandlerType_name, int32(x))
}

func (HandlerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_565b712cd72dd24a, []int{1}
}

// Identity is a protocol buffers representation of the configkit.Identity type.
type Identity struct {
	// Name is the entity's unique name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Key is the entity's immutable, unique key.
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_565b712cd72dd24a, []int{0}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Identity) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// Application is a protocol buffers representation of the configkit.Application
// interface.
type Application struct {
	// Identity is the application's identity.
	Identity *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// TypeName is the fully-qualified name of the Go type used to implement the
	// application.
	TypeName string `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	// Messages is an ordered-sequence of message name / role pairs.
	//
	// This directly correlates to the configkit.Application.MessageNames().Roles
	// value. The produced/consumed message names are not encoded directly in the
	// application, but rather rebuilt from the handlers when the application is
	// unmarshaled.
	Messages []*NameRole `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	// Handlers is the set of handlers within the application.
	Handlers             []*Handler `protobuf:"bytes,4,rep,name=handlers,proto3" json:"handlers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_565b712cd72dd24a, []int{1}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Application) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *Application) GetMessages() []*NameRole {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *Application) GetHandlers() []*Handler {
	if m != nil {
		return m.Handlers
	}
	return nil
}

// NameRole is a 2-tuple containing a message name and its role.
type NameRole struct {
	// Name is the fully-qualified message name.
	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Role is the role this message plays within the application.
	Role                 MessageRole `protobuf:"varint,2,opt,name=role,proto3,enum=dogma.config.v1.MessageRole" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NameRole) Reset()         { *m = NameRole{} }
func (m *NameRole) String() string { return proto.CompactTextString(m) }
func (*NameRole) ProtoMessage()    {}
func (*NameRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_565b712cd72dd24a, []int{2}
}

func (m *NameRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameRole.Unmarshal(m, b)
}
func (m *NameRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameRole.Marshal(b, m, deterministic)
}
func (m *NameRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameRole.Merge(m, src)
}
func (m *NameRole) XXX_Size() int {
	return xxx_messageInfo_NameRole.Size(m)
}
func (m *NameRole) XXX_DiscardUnknown() {
	xxx_messageInfo_NameRole.DiscardUnknown(m)
}

var xxx_messageInfo_NameRole proto.InternalMessageInfo

func (m *NameRole) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *NameRole) GetRole() MessageRole {
	if m != nil {
		return m.Role
	}
	return MessageRole_UNKNOWN_MESSAGE_ROLE
}

// Handler is a protocol buffers representation of the configkit.Handler
// interface.
type Handler struct {
	// Identity is the handler's identity.
	Identity *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// TypeName is the fully-qualified name of the Go type used to implement the
	// handler.
	TypeName string `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	// Type is the handler's type.
	Type HandlerType `protobuf:"varint,3,opt,name=type,proto3,enum=dogma.config.v1.HandlerType" json:"type,omitempty"`
	// Produced is a list of the messages produced by this handler.
	// Each value is the index of a MessageRolePair within the application.
	Produced []uint32 `protobuf:"varint,4,rep,packed,name=produced,proto3" json:"produced,omitempty"`
	// Consumed is a list of the messages consumed by this handler.
	// Each value is the index of a MessageRolePair within the application.
	Consumed             []uint32 `protobuf:"varint,5,rep,packed,name=consumed,proto3" json:"consumed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handler) Reset()         { *m = Handler{} }
func (m *Handler) String() string { return proto.CompactTextString(m) }
func (*Handler) ProtoMessage()    {}
func (*Handler) Descriptor() ([]byte, []int) {
	return fileDescriptor_565b712cd72dd24a, []int{3}
}

func (m *Handler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handler.Unmarshal(m, b)
}
func (m *Handler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handler.Marshal(b, m, deterministic)
}
func (m *Handler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handler.Merge(m, src)
}
func (m *Handler) XXX_Size() int {
	return xxx_messageInfo_Handler.Size(m)
}
func (m *Handler) XXX_DiscardUnknown() {
	xxx_messageInfo_Handler.DiscardUnknown(m)
}

var xxx_messageInfo_Handler proto.InternalMessageInfo

func (m *Handler) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Handler) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *Handler) GetType() HandlerType {
	if m != nil {
		return m.Type
	}
	return HandlerType_UNKNOWN_HANDLER_TYPE
}

func (m *Handler) GetProduced() []uint32 {
	if m != nil {
		return m.Produced
	}
	return nil
}

func (m *Handler) GetConsumed() []uint32 {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func init() {
	proto.RegisterEnum("dogma.config.v1.MessageRole", MessageRole_name, MessageRole_value)
	proto.RegisterEnum("dogma.config.v1.HandlerType", HandlerType_name, HandlerType_value)
	proto.RegisterType((*Identity)(nil), "dogma.config.v1.Identity")
	proto.RegisterType((*Application)(nil), "dogma.config.v1.Application")
	proto.RegisterType((*NameRole)(nil), "dogma.config.v1.NameRole")
	proto.RegisterType((*Handler)(nil), "dogma.config.v1.Handler")
}

func init() {
	proto.RegisterFile("api/internal/pb/types.proto", fileDescriptor_565b712cd72dd24a)
}

var fileDescriptor_565b712cd72dd24a = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0xb1, 0x4b, 0x9d, 0x31, 0x6d, 0xad, 0x15, 0x07, 0x43, 0x39, 0x54, 0x39, 0xa1, 0x4a,
	0xd8, 0xa1, 0xd0, 0x0f, 0x30, 0xe9, 0xca, 0x0d, 0xc4, 0x76, 0xb4, 0x71, 0x41, 0x70, 0x89, 0x1c,
	0x7b, 0x49, 0x57, 0xb5, 0xbd, 0xc6, 0xde, 0x20, 0xe5, 0x0b, 0xb9, 0xf1, 0x4d, 0x68, 0xd7, 0x49,
	0x14, 0x5a, 0x38, 0xf6, 0x36, 0x33, 0xfb, 0xe6, 0xbd, 0xb7, 0x4f, 0x1a, 0x38, 0x4d, 0x6b, 0xe6,
	0xb1, 0x4a, 0xd0, 0xa6, 0x4a, 0x0b, 0xaf, 0x5e, 0x78, 0x62, 0x5d, 0xd3, 0xd6, 0xad, 0x1b, 0x2e,
	0x38, 0x3a, 0xc9, 0xf9, 0xb2, 0x4c, 0xdd, 0x8c, 0x57, 0xdf, 0xd9, 0xd2, 0xfd, 0xf9, 0x76, 0x30,
	0x04, 0x73, 0x9c, 0xd3, 0x4a, 0x30, 0xb1, 0x46, 0x08, 0x8c, 0x2a, 0x2d, 0xa9, 0xa3, 0x9d, 0x69,
	0xaf, 0xfb, 0x44, 0xd5, 0xc8, 0x06, 0xfd, 0x8e, 0xae, 0x9d, 0x9e, 0x1a, 0xc9, 0x72, 0xf0, 0x5b,
	0x03, 0xcb, 0xaf, 0xeb, 0x82, 0x65, 0xa9, 0x60, 0xbc, 0x42, 0x97, 0x60, 0xb2, 0x0d, 0x83, 0xda,
	0xb4, 0x2e, 0x5e, 0xb8, 0xf7, 0x54, 0xdc, 0xad, 0x04, 0xd9, 0x41, 0xd1, 0x29, 0xf4, 0xa5, 0xb1,
	0xb9, 0x52, 0xec, 0xe8, 0x4d, 0x39, 0x88, 0xa4, 0xea, 0x25, 0x98, 0x25, 0x6d, 0xdb, 0x74, 0x49,
	0x5b, 0x47, 0x3f, 0xd3, 0xff, 0xc9, 0x29, 0x81, 0x84, 0x17, 0x94, 0xec, 0xa0, 0xe8, 0x3d, 0x98,
	0xb7, 0x69, 0x95, 0x17, 0xb4, 0x69, 0x1d, 0x43, 0xad, 0x39, 0x0f, 0xd6, 0xae, 0x3b, 0x00, 0xd9,
	0x21, 0x07, 0x53, 0x30, 0xb7, 0x5c, 0x7f, 0x45, 0xf0, 0x6c, 0x13, 0xc1, 0x10, 0x8c, 0x86, 0x17,
	0x9d, 0xc9, 0xe3, 0x8b, 0x57, 0x0f, 0x18, 0xc3, 0x4e, 0x5e, 0x79, 0x51, 0xc8, 0xc1, 0x2f, 0x0d,
	0x0e, 0x37, 0x3a, 0x8f, 0x12, 0xcf, 0x10, 0x0c, 0x59, 0x3b, 0xfa, 0x7f, 0x1c, 0x6d, 0xb4, 0x93,
	0x75, 0x4d, 0x89, 0x42, 0xa2, 0x97, 0x60, 0xd6, 0x0d, 0xcf, 0x57, 0x19, 0xcd, 0x55, 0x32, 0x47,
	0x64, 0xd7, 0xcb, 0xb7, 0x8c, 0x57, 0xed, 0xaa, 0xa4, 0xb9, 0x73, 0xd0, 0xbd, 0x6d, 0xfb, 0xf3,
	0x09, 0x58, 0x7b, 0xdf, 0x43, 0x0e, 0x3c, 0xbf, 0x89, 0x3e, 0x45, 0xf1, 0x97, 0x68, 0x1e, 0xe2,
	0xd9, 0xcc, 0x0f, 0xf0, 0x9c, 0xc4, 0x13, 0x6c, 0x3f, 0x41, 0x16, 0x1c, 0x8e, 0xe2, 0x30, 0xf4,
	0xa3, 0x2b, 0x5b, 0x43, 0x7d, 0x38, 0xc0, 0x9f, 0x71, 0x94, 0xd8, 0x3d, 0x39, 0x4f, 0xc6, 0x21,
	0x8e, 0x6f, 0x12, 0x5b, 0x3f, 0xcf, 0xc1, 0xda, 0xb3, 0xb6, 0xcf, 0x76, 0xed, 0x47, 0x57, 0x13,
	0x4c, 0xe6, 0xc9, 0xd7, 0xa9, 0x64, 0x3b, 0x82, 0xbe, 0x1f, 0x04, 0x04, 0x07, 0x7e, 0x82, 0x6d,
	0x4d, 0x92, 0x4c, 0x49, 0x3c, 0xc2, 0xb3, 0x99, 0xdd, 0x43, 0x27, 0x60, 0x8d, 0xa3, 0x04, 0x07,
	0xc4, 0x4f, 0xc6, 0x71, 0x64, 0xeb, 0xe8, 0x18, 0x60, 0x4a, 0xe2, 0x8f, 0x78, 0xa4, 0x7a, 0xe3,
	0x83, 0xf7, 0xed, 0xcd, 0x92, 0x89, 0xdb, 0xd5, 0xc2, 0xcd, 0x78, 0xe9, 0xa9, 0x6c, 0x04, 0xfb,
	0xe1, 0x75, 0xf1, 0xdc, 0x31, 0xe1, 0xdd, 0x3b, 0x90, 0xc5, 0x53, 0x75, 0x1b, 0xef, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xde, 0x6e, 0x6c, 0x0c, 0x3a, 0x03, 0x00, 0x00,
}
